import pg from "pg";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not set");
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const analysis = {
  id: `analysis_seed_1`,
  video_url: "https://www.youtube.com/live/PRem1_S56W8",
  video_title: "Indian Athletic Series 3 – 2024",
  analyzed_at: new Date().toISOString(),
  total_duration_hours: 12,
  total_events: 20,
  total_athletes: 210,
  total_races: 13,
  events: JSON.stringify([
    {
      id: "evt_1",
      eventName: "100m Men Heats",
      category: "sprint",
      gender: "men",
      startTimestamp: "00:12:00",
      endTimestamp: "00:28:00",
      athletes: [
        { rank: 1, name: "Amlan Borgohain", result: "10.28s", notes: "Season Best" },
        { rank: 2, name: "Gurindervir Singh", result: "10.34s" },
        { rank: 3, name: "Manikanda Rajan", result: "10.39s" },
      ],
      highlightMoment: "Borgohain blazes through the heats with a blistering 10.28s — fastest Indian of the season",
      intensityScore: 8,
      winningResult: "10.28s",
      notes: "Three heats run back-to-back",
    },
    {
      id: "evt_2",
      eventName: "100m Men Final",
      category: "sprint",
      gender: "men",
      startTimestamp: "00:45:10",
      endTimestamp: "00:47:30",
      athletes: [
        { rank: 1, name: "Amlan Borgohain", result: "10.24s", notes: "National Record equalled" },
        { rank: 2, name: "Gurindervir Singh", result: "10.31s" },
        { rank: 3, name: "Srinivas Gowda", result: "10.38s" },
      ],
      highlightMoment: "Borgohain dips at the line to equal the national record — stadium erupts",
      intensityScore: 10,
      winningResult: "10.24s",
      notes: "Closest final of the meet — 0.07s separated 1st and 2nd",
    },
    {
      id: "evt_3",
      eventName: "100m Women Final",
      category: "sprint",
      gender: "women",
      startTimestamp: "01:05:00",
      endTimestamp: "01:07:20",
      athletes: [
        { rank: 1, name: "Dutee Chand", result: "11.38s" },
        { rank: 2, name: "Hima Das", result: "11.44s" },
        { rank: 3, name: "Srabani Nanda", result: "11.52s" },
      ],
      highlightMoment: "Dutee Chand storms home in 11.38s with an electrifying lean at the tape",
      intensityScore: 9,
      winningResult: "11.38s",
    },
    {
      id: "evt_4",
      eventName: "200m Men Final",
      category: "sprint",
      gender: "men",
      startTimestamp: "01:35:00",
      endTimestamp: "01:37:30",
      athletes: [
        { rank: 1, name: "Amlan Borgohain", result: "20.75s", notes: "Meet Record" },
        { rank: 2, name: "Noah Nirmal Tom", result: "20.89s" },
        { rank: 3, name: "Selvamani K", result: "21.05s" },
      ],
      highlightMoment: "Borgohain powers around the bend and surges down the straight to a meet record 20.75s",
      intensityScore: 9,
      winningResult: "20.75s",
      notes: "Meet record broken",
    },
    {
      id: "evt_5",
      eventName: "400m Men Final",
      category: "sprint",
      gender: "men",
      startTimestamp: "02:10:00",
      endTimestamp: "02:13:00",
      athletes: [
        { rank: 1, name: "Muhammad Anas Yahiya", result: "45.48s" },
        { rank: 2, name: "Rajiv Arokia", result: "45.72s" },
        { rank: 3, name: "Naganathan Pandi", result: "46.01s" },
      ],
      highlightMoment: "Anas kicks clear with 100m to go in a tactically brilliant race",
      intensityScore: 8,
      winningResult: "45.48s",
    },
    {
      id: "evt_6",
      eventName: "400m Women Final",
      category: "sprint",
      gender: "women",
      startTimestamp: "02:40:00",
      endTimestamp: "02:42:30",
      athletes: [
        { rank: 1, name: "Vithya Ramraj", result: "51.23s", notes: "Season Best" },
        { rank: 2, name: "Priya H Mohan", result: "51.68s" },
        { rank: 3, name: "Subha Venkatesan", result: "52.14s" },
      ],
      highlightMoment: "Vithya Ramraj produces a dominant back-straight surge to win by 0.45s",
      intensityScore: 8,
      winningResult: "51.23s",
    },
    {
      id: "evt_7",
      eventName: "800m Men Final",
      category: "middle_distance",
      gender: "men",
      startTimestamp: "03:20:00",
      endTimestamp: "03:22:30",
      athletes: [
        { rank: 1, name: "Jinson Johnson", result: "1:45.82" },
        { rank: 2, name: "Ajay Kumar Saroj", result: "1:46.14" },
        { rank: 3, name: "Krishankant Sharma", result: "1:46.89" },
      ],
      highlightMoment: "Johnson and Saroj sprint side-by-side in a breathless finish — separated by only 0.32s",
      intensityScore: 9,
      winningResult: "1:45.82",
    },
    {
      id: "evt_8",
      eventName: "1500m Men Final",
      category: "middle_distance",
      gender: "men",
      startTimestamp: "04:05:00",
      endTimestamp: "04:09:00",
      athletes: [
        { rank: 1, name: "Adille Sumariwalla", result: "3:36.42" },
        { rank: 2, name: "Avinash Sable", result: "3:36.89" },
        { rank: 3, name: "Samuel Tirkey", result: "3:38.14" },
      ],
      highlightMoment: "A last-lap surge turns this into a sprint finish — three athletes within 2 seconds",
      intensityScore: 8,
      winningResult: "3:36.42",
    },
    {
      id: "evt_9",
      eventName: "5000m Men Final",
      category: "long_distance",
      gender: "men",
      startTimestamp: "04:55:00",
      endTimestamp: "05:09:00",
      athletes: [
        { rank: 1, name: "Avinash Sable", result: "13:25.65" },
        { rank: 2, name: "Kartik Kumar", result: "13:28.01" },
        { rank: 3, name: "Gulveer Singh", result: "13:30.42" },
      ],
      highlightMoment: "Sable breaks away with two laps to go in a tactical masterclass",
      intensityScore: 7,
      winningResult: "13:25.65",
    },
    {
      id: "evt_10",
      eventName: "110m Hurdles Men Final",
      category: "hurdles",
      gender: "men",
      startTimestamp: "05:45:00",
      endTimestamp: "05:47:20",
      athletes: [
        { rank: 1, name: "Siddhanth Thingalaya", result: "13.81s", notes: "Season Best" },
        { rank: 2, name: "Tejaswin Shankar", result: "13.95s" },
        { rank: 3, name: "Abdul Hafiz", result: "14.12s" },
      ],
      highlightMoment: "Thingalaya is flawless over the barriers — smooth mechanics give him a clear win",
      intensityScore: 8,
      winningResult: "13.81s",
    },
    {
      id: "evt_11",
      eventName: "400m Hurdles Women Final",
      category: "hurdles",
      gender: "women",
      startTimestamp: "06:20:00",
      endTimestamp: "06:22:40",
      athletes: [
        { rank: 1, name: "Vithya Ramraj", result: "55.42s" },
        { rank: 2, name: "Pallavi Singh", result: "56.18s" },
        { rank: 3, name: "Anu Raghavan", result: "56.74s" },
      ],
      highlightMoment: "Ramraj clears every hurdle in rhythm and powers home in an authoritative display",
      intensityScore: 8,
      winningResult: "55.42s",
    },
    {
      id: "evt_12",
      eventName: "4x100m Men Relay Final",
      category: "relay",
      gender: "men",
      startTimestamp: "07:10:00",
      endTimestamp: "07:12:30",
      athletes: [
        { rank: 1, name: "Tamil Nadu", result: "39.12s", notes: "State Record" },
        { rank: 2, name: "Haryana", result: "39.41s" },
        { rank: 3, name: "Karnataka", result: "39.58s" },
      ],
      highlightMoment: "Tamil Nadu's baton changes are flawless — they run a blazing state record to take gold",
      intensityScore: 10,
      winningResult: "39.12s",
      notes: "State record for Tamil Nadu",
    },
    {
      id: "evt_13",
      eventName: "4x400m Women Relay Final",
      category: "relay",
      gender: "women",
      startTimestamp: "07:50:00",
      endTimestamp: "07:53:30",
      athletes: [
        { rank: 1, name: "Kerala", result: "3:31.24" },
        { rank: 2, name: "Tamil Nadu", result: "3:32.01" },
        { rank: 3, name: "Punjab", result: "3:33.88" },
      ],
      highlightMoment: "Kerala's anchor leg produces a stunning comeback to overtake Tamil Nadu in the home straight",
      intensityScore: 9,
      winningResult: "3:31.24",
    },
    {
      id: "evt_14",
      eventName: "Long Jump Men Final",
      category: "jump",
      gender: "men",
      startTimestamp: "03:00:00",
      endTimestamp: "03:15:00",
      athletes: [
        { rank: 1, name: "Murali Sreeshankar", result: "8.09m", notes: "Season Best" },
        { rank: 2, name: "Jeswin Aldrin", result: "7.98m" },
        { rank: 3, name: "Shaili Singh", result: "7.89m" },
      ],
      highlightMoment: "Sreeshankar launches to 8.09m on his fifth attempt — crowd on their feet",
      intensityScore: 9,
      winningResult: "8.09m",
    },
    {
      id: "evt_15",
      eventName: "Long Jump Women Final",
      category: "jump",
      gender: "women",
      startTimestamp: "03:45:00",
      endTimestamp: "03:58:00",
      athletes: [
        { rank: 1, name: "Shaili Singh", result: "6.63m" },
        { rank: 2, name: "Nayana James", result: "6.41m" },
        { rank: 3, name: "Ancy Sojan", result: "6.38m" },
      ],
      highlightMoment: "Singh soars to 6.63m with a near-perfect run-up and takeoff",
      intensityScore: 8,
      winningResult: "6.63m",
    },
    {
      id: "evt_16",
      eventName: "High Jump Men Final",
      category: "jump",
      gender: "men",
      startTimestamp: "08:30:00",
      endTimestamp: "09:00:00",
      athletes: [
        { rank: 1, name: "Tejaswin Shankar", result: "2.28m" },
        { rank: 2, name: "Sarvesh Kusare", result: "2.24m" },
        { rank: 3, name: "Akshdeep Singh", result: "2.20m" },
      ],
      highlightMoment: "Shankar clears 2.28m on his first attempt to deliver a masterclass in technique",
      intensityScore: 9,
      winningResult: "2.28m",
    },
    {
      id: "evt_17",
      eventName: "Triple Jump Men Final",
      category: "jump",
      gender: "men",
      startTimestamp: "09:15:00",
      endTimestamp: "09:35:00",
      athletes: [
        { rank: 1, name: "Praveen Chithravel", result: "16.68m" },
        { rank: 2, name: "Eldhose Paul", result: "16.54m" },
        { rank: 3, name: "Abdulla Aboobacker", result: "16.41m" },
      ],
      highlightMoment: "Chithravel's third hop is explosive — he lands at 16.68m to lead a top-three all above 16.40m",
      intensityScore: 9,
      winningResult: "16.68m",
      notes: "All three medal positions exceeded 16.40m — world class depth",
    },
    {
      id: "evt_18",
      eventName: "Javelin Throw Men Final",
      category: "throw",
      gender: "men",
      startTimestamp: "06:50:00",
      endTimestamp: "07:05:00",
      athletes: [
        { rank: 1, name: "Neeraj Chopra", result: "88.17m" },
        { rank: 2, name: "Kishore Kumar Jena", result: "84.05m" },
        { rank: 3, name: "DP Manu", result: "82.44m" },
      ],
      highlightMoment: "Chopra unleashes a laser-straight 88.17m throw — the entire stadium rises as one",
      intensityScore: 10,
      winningResult: "88.17m",
      notes: "Neeraj Chopra's appearance draws largest crowd of the day",
    },
    {
      id: "evt_19",
      eventName: "Shot Put Men Final",
      category: "throw",
      gender: "men",
      startTimestamp: "05:00:00",
      endTimestamp: "05:15:00",
      athletes: [
        { rank: 1, name: "Tajinderpal Singh Toor", result: "20.32m", notes: "Season Best" },
        { rank: 2, name: "Abha Khatua", result: "19.41m" },
        { rank: 3, name: "Karanvir Singh", result: "18.88m" },
      ],
      highlightMoment: "Toor spins powerfully and explodes the shot to 20.32m — a commanding performance",
      intensityScore: 8,
      winningResult: "20.32m",
    },
    {
      id: "evt_20",
      eventName: "20km Race Walk Men",
      category: "walk",
      gender: "men",
      startTimestamp: "10:00:00",
      endTimestamp: "11:25:00",
      athletes: [
        { rank: 1, name: "Akshdeep Singh", result: "1:20:15", notes: "National Record" },
        { rank: 2, name: "Sandeep Kumar", result: "1:21:08" },
        { rank: 3, name: "Paramjeet Singh Bisht", result: "1:22:44" },
      ],
      highlightMoment: "Akshdeep Singh crosses the line in a national record — arms raised, overcome with emotion",
      intensityScore: 8,
      winningResult: "1:20:15",
      notes: "National Record set in hot and humid conditions",
    },
  ]),
  highlights: JSON.stringify([
    {
      timestamp: "00:01:00",
      caption: "The stadium fills — India's finest athletes gather for the showdown",
      eventName: "Opening Ceremony",
      type: "crowd_reaction",
      reelPosition: 1,
    },
    {
      timestamp: "00:45:10",
      caption: "Borgohain equals the national record — 10.24s of pure electricity",
      eventName: "100m Men Final",
      type: "finish_line",
      reelPosition: 2,
    },
    {
      timestamp: "01:05:45",
      caption: "Dutee Chand storms to victory in a stunning 11.38s",
      eventName: "100m Women Final",
      type: "winner_reaction",
      reelPosition: 3,
    },
    {
      timestamp: "03:02:30",
      caption: "Sreeshankar launches to 8.09m — an extraordinary season best",
      eventName: "Long Jump Men Final",
      type: "field_attempt",
      reelPosition: 4,
    },
    {
      timestamp: "05:46:00",
      caption: "Neeraj Chopra's 88.17m javelin throw — the crowd erupts",
      eventName: "Javelin Throw Men Final",
      type: "field_attempt",
      reelPosition: 5,
    },
    {
      timestamp: "07:10:30",
      caption: "Tamil Nadu relay team smashes state record with 39.12s baton perfection",
      eventName: "4x100m Men Relay Final",
      type: "finish_line",
      reelPosition: 6,
    },
    {
      timestamp: "07:52:45",
      caption: "Kerala's anchor storms past Tamil Nadu — unbelievable comeback relay win",
      eventName: "4x400m Women Relay Final",
      type: "winner_reaction",
      reelPosition: 7,
    },
    {
      timestamp: "08:45:00",
      caption: "Shankar clears 2.28m on first attempt — flawless Fosbury Flop",
      eventName: "High Jump Men Final",
      type: "field_attempt",
      reelPosition: 8,
    },
    {
      timestamp: "09:18:00",
      caption: "Chithravel lands at 16.68m — triple jump gold decided in spectacular fashion",
      eventName: "Triple Jump Men Final",
      type: "field_attempt",
      reelPosition: 9,
    },
    {
      timestamp: "11:25:00",
      caption: "Akshdeep Singh crosses the line — national record and unrestrained joy",
      eventName: "20km Race Walk Men",
      type: "record_broken",
      reelPosition: 10,
    },
  ]),
  reel_structure: JSON.stringify([
    {
      order: 1,
      label: "hook",
      description: "Stadium atmosphere — floodlights, packed crowd, India's best athletes on the start line",
      timestamps: ["00:01:00", "00:44:50"],
      durationSeconds: 4,
    },
    {
      order: 2,
      label: "track_events",
      description: "Sprint starts, photo finishes, and relay baton exchanges — track fire",
      timestamps: ["00:45:10", "01:05:45", "01:35:00", "02:10:00", "07:10:30"],
      durationSeconds: 9,
    },
    {
      order: 3,
      label: "field_events",
      description: "Long jump landings, javelin releases, high jump clearances",
      timestamps: ["03:02:30", "05:46:00", "08:45:00", "09:18:00"],
      durationSeconds: 7,
    },
    {
      order: 4,
      label: "climax",
      description: "The most dramatic and record-breaking moments of the day",
      timestamps: ["07:52:45", "11:25:00"],
      durationSeconds: 6,
    },
    {
      order: 5,
      label: "ending",
      description: "Medal ceremony, athlete celebrations, and closing moments",
      timestamps: ["11:45:00"],
      durationSeconds: 3,
    },
  ]),
  analysis_summary:
    "The Indian Athletic Series 3 delivered a day of exceptional performances across all disciplines, drawing a partisan crowd that was treated to some of the finest athletics seen on Indian soil in recent years. Amlan Borgohain headlined the sprints by equalling the national 100m record in an electric final, while Neeraj Chopra's 88.17m javelin throw drew the day's largest standing ovation. The field events showcased India's growing technical depth — Sreeshankar's 8.09m long jump, Chithravel and Paul trading world-class triple jumps above 16.54m, and Tejaswin Shankar's elegant 2.28m high jump all demonstrated that Indian athletics is no longer just a sprint nation. Relay teams produced the afternoon's most breathless moments, with Tamil Nadu's 4x100m men shattering their state record and Kerala's women delivering a stunning anchor-leg comeback. The meet closed with Akshdeep Singh setting a national record in the 20km race walk — an emotional finish that perfectly summarised a day when Indian athletics stepped firmly into the global spotlight.",
  selection_rationale:
    "Moments were selected on four criteria: motion intensity (explosive starts, field event release points, sprint finishes), competitive drama (sub-0.1s margins, last-lap surges, relay near-misses), crowd reaction (Chopra's javelin and the national record moments registered the highest audible response), and historical significance (national and state records, season bests above global qualification standards). The 10 chosen highlights represent the full breadth of the programme — sprints, jumps, throws, relays, and walks — ensuring the reel tells a complete story of Indian athletics in one 28-second package.",
};

async function seed() {
  try {
    await pool.query("DELETE FROM video_analysis");

    await pool.query(
      `INSERT INTO video_analysis
         (id, video_url, video_title, analyzed_at, total_duration_hours,
          total_events, total_athletes, total_races, events, highlights,
          reel_structure, analysis_summary, selection_rationale)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,
      [
        analysis.id,
        analysis.video_url,
        analysis.video_title,
        analysis.analyzed_at,
        analysis.total_duration_hours,
        analysis.total_events,
        analysis.total_athletes,
        analysis.total_races,
        analysis.events,
        analysis.highlights,
        analysis.reel_structure,
        analysis.analysis_summary,
        analysis.selection_rationale,
      ]
    );

    console.log("Seed complete — inserted analysis with 20 events and 10 highlights");
  } finally {
    await pool.end();
  }
}

seed().catch((err) => {
  console.error("Seed failed:", err.message);
  process.exit(1);
});
